require('main.events.filter')
require('wishlist.events.platforms')
require('main.events.search')
require('wishlist.events.skin')
require('wishlist.events.slots')
require('main.events.sort')
require('wishlist.events.toolbar')
