[Variables]
;Path to where Steam is installed.
SteamPath=

;UserDataID corresponding to your Steam account.
UserDataID=

;Paths to Steam libraries that are not located in the same place as your Steam installation. Multiple paths can be separated with a semicolon (;).
SteamLibraryPaths=

;Width of a game's banner in pixels. Default value is 274.
BannerWidth=274

;Height of a game's banner in pixels. Default value is 128.
BannerHeight=128

;0 = invisible, 255 = opaque.
BannerOpacity=255

;Number of slots that can display a banner.
SlotCount=6

;0 = vertical up to down, 1 = horizontal left to right.
Orientation=0

;The amount to multiply the movement when scrolling. Default value is 1.
ScrollMultiplier=1

;Color and opacity of background (red, green, blue, opacity).
BackgroundColor=0,0,0,128

;Color and opacity of toolbar background (red, green, blue, opacity).
ToolbarBackgroundColor=0,0,0,191

;The interval between checks for new games. Unit is seconds. -1 = only check upon the skin being initialized/refreshed.
RefreshInterval=-1

;Hide status messages
HideMessages=0